version: '3.4'
services:
  db:
    image: postgres:11.6
    environment:
      POSTGRES_DB: clean_house
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  app:
    build:
      context: .
    depends_on:
      - db
    command: ["cat"]
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      HOST: localhost:3000
